- name: Stop services
  ansible.windows.win_service:
    name: "{{ item.item }}"
    state: stopped
  loop: "{{ service_info.results }}"
  when: 
    - item.exists
  no_log: true  # Verhindert die Ausgabe detaillierter Informationen
  ignore_errors: yes