- name: Get service status (Windows)
  ansible.windows.win_service_info:
    name: "{{ item }}"
  register: service_info
  loop:
    - Spooler
    - CogonCalculationService
    - CogonCommonService
    - CogonCommunicationService
    - CogonMonitoringProcess
    - CogonPathMonitoringService
    - CogonReportingService
    - CogonServiceManager
    - CogonShadowAccountingService
    - glpi-agent
    - Sophos File Scanner Service
    - Sophos Health Service
    - Sophos Live Query
    - Sophos MCS Agent
    - Sophos MCS Client
    - Sophos System Protection Service