- name: Ensure directory exists
  ansible.builtin.file:
    path: /mnt/protokolle/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/Serverpatch/@work
    state: directory
    recurse: yes
  delegate_to: localhost

- name: Ensure log file exists
  ansible.builtin.file:
    path: /mnt/protokolle/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/Serverpatch/@work/Updates-{{ groupe_name }}-Generated.txt
    state: touch
  delegate_to: localhost

# - name: Parse the JSON output
#   set_fact:
#     parsed_logs: "{{ event_logs.stdout_lines | join('') | from_json }}"

- name: Write log
  ansible.builtin.lineinfile:
    path: /mnt/protokolle/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/Serverpatch/@work/Updates-{{ groupe_name }}-Generated.txt
    line: |
      ---------------------------------------------------------------------------------------------------------------------------

      {{ inventory_hostname }} ({{ ansible_facts.os_name | default('unbekannt') }}):
        Updates({{ update_result.found_update_count | default(0) }}):
        {% for update in update_result.updates | default({}) %}
          - {{ update_result.updates[update].title }}
        {% endfor %}

        Done: Neustart von {{ reboot_start.stdout | default('unbekannt') }} bis {{ reboot_end.stdout | default('unbekannt') }} = {{ 'FEHLER' if patch_error != '' else 'OK' }}
        {{ windows_diskspace_check | default('ToDo: Festplattenspeicher = (nicht ermittelt)') }}
        {{ windows_verson_check | default('ToDo: Versionsupdate = (nicht ermittelt)') }}
        {% if patch_error != '' %}
        {{ patch_error }}
        {% endif %}
        ToDo: WSUS Status prüfen =
        ToDo: Logs > Anwendung und System:
        ToDo: Abmelden =
  delegate_to: localhost