- name: Get WSUS status
  hosts: wsus2
  
  vars_prompt:
  - name: ansible_user
    prompt: "Admin (bsp. adminjs@gutingia.local)"
    private: false
  - name: ansible_password
    prompt: "Passwort"
    private: true
  
  tasks:
    - name: Copy PowerShell script to the server
      win_copy:
        src: /opt/ansible-assets/powershell/scripts/Get-WsusStatus.ps1
        dest: C:\Temp\Get-WsusStatus.ps1

    - name: Run PowerShell script to get WSUS status
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Temp\Get-WsusStatus.ps1
      register: wsus_status

    - name: Display WSUS status
      debug:
        var: wsus_status.stdout
