---
- name: Erstelle einen Snapshot von einer virtuellen Maschine
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware

  tasks:
    - name: Zeige das Ergebnis des PowerShell-Skripts
      debug:
        msg: "{{ inventory_hostname }}"

    - name: create snapshot
      vmware_guest_snapshot:
        hostname: vcenter1.gutingia.local
        username: "{{ domain_admin_user }}"
        password: "{{ domain_admin_password }}"
        datacenter: myLife
        validate_certs: false
        name: "{{ inventory_hostname }}"
        state: present
        snapshot_name: "Ansible Managed Snapshot"
        folder: myLife
        description: "This snapshot is created by Ansible Playbook"
        memory_dump: true
      delegate_to: localhost
