---
- name: Beispiel-Playbook mit Benutzerinteraktion und Wiederholung
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Initialisiere den Zähler
      set_fact:
        attempts: 0

    - name: Frage den Benutzer nach einer Option
      pause:
        prompt: "Wähle eine Option (1/2/3): "
        echo: yes
      register: user_choice

    - name: Überprüfe die Benutzerauswahl
      set_fact:
        attempts: "{{ attempts + 1 }}"
      when: user_choice.user_input not in ["1", "2", "3"]

    - name: Zeige die vom Benutzer ausgewählte Option
      debug:
        msg: "Benutzer hat die Option {{ user_choice.user_input }} ausgewählt."
      when: user_choice.user_input in ["1", "2", "3"]

    - name: Überprüfe, ob der Zähler das Maximum erreicht hat
      fail:
        msg: "Maximale Anzahl von Versuchen erreicht."
      when: attempts >= 3
