- name: Konfiguriere SSH-Schl端ssel auf einem Server
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: target_host
      prompt: "Gib den Servernamen oder die IP-Adresse ein"
      private: no

    - name: remote_user
      prompt: "Gib den Benutzernamen f端r den Server ein"
      private: no

    - name: remote_pass
      prompt: "Gib das Passwort f端r den Server ein"
      private: yes

  tasks:
    - name: Stelle sicher, dass der SSH-Schl端ssel vorhanden ist
      ansible.builtin.authorized_key:
        user: "{{ remote_user }}"
        state: present
        key: "{{ lookup('file', '/pfad/zu/deinem/public_key.pub') }}"
      delegate_to: "{{ target_host }}"
      vars:
        ansible_user: "{{ remote_user }}"
        ansible_ssh_pass: "{{ remote_pass }}"
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3