- name: Install Metricbeat on Linux servers
  hosts: linux_server
  become: yes

  tasks:
    - name: Check if Metricbeat is already installed
      ansible.builtin.command: dpkg -l metricbeat
      changed_when: false
      register: metricbeat_status
      ignore_errors: true

    - name: Import Elastic GPG key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: metricbeat_status.rc != 0

    - name: Remove wrong Source List file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/artifacts_elastic_co_packages_8_x_apt.list
        state: absent

    - name: Add Elastic APT repository
      ansible.builtin.apt_repository:
        filename: "elastic-source.list"
        repo: "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Metricbeat
      ansible.builtin.apt:
        name: metricbeat
        state: present
      when: metricbeat_status.rc != 0

    - name: Copy Metricbeat configuration file
      ansible.builtin.copy:
        src: metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
      when: metricbeat_status.rc != 0

    - name: Start Metricbeat service
      ansible.builtin.service:
        name: metricbeat
        state: started
        enabled: yes
      when: metricbeat_status.rc != 0
