---
- name: Install WordPress
#  hosts: localhost
#  gather_facts: False
#  tasks:
#    - name: Prompt for the target server
#      vars_prompt:
#        - name: server_host
#          prompt: "Enter the target server (IP address or hostname):"
#
#    - name: Set facts with user input
#      set_fact:
#        ansible_host: "{{ server_host }}"
  hosts:  linux_web_server #"{{ ansible_host }}"
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      tags: ['packages']

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
      tags: ['packages']

    - name: Set proxy environment variables
      ansible.builtin.set_fact:
        env:
          http_proxy: "http://proxy:8080"
          https_proxy: "http://proxy:8080"

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress-latest.tar.gz"
        validate_certs: no
      tags: ['wordpress']
      environment: "{{ env }}"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress-latest.tar.gz"
        dest: "/var/www/html/"
        owner: www-data
        group: www-data
        remote_src: yes
      tags: ['wordpress']

#    - name: Configure WordPress
#      template:
#        src: wp-config.php.j2
#        dest: "/var/www/html/wordpress/wp-config.php"
#        owner: www-data
#        group: www-data
#        mode: 0640
#      tags: ['wordpress']

    - name: Create Database
      mysql_db:
        name: mywordpress
        state: present
      tags: ['wordpress']

    - name: Create Database User
      mysql_user:
        name: mywpuser
        password: mywppassword
        priv: "mywordpress.*:ALL"
        state: present
      tags: ['wordpress']

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      tags: ['wordpress']
