---
- name: Erstelle Snapshots
  hosts: windows_test
  become: false
  gather_facts: true

  tasks:
  - name: Führe PowerShell-Befehl ohne Benutzerprofile aus
    ansible.windows.win_shell: |
      powershell.exe -NoProfile -Command '"{0:N2}" -f (Get-PSDrive C | Select-Object Free | ForEach-Object { $_.Free / 1GB })'
    register: ps_output
  
  - name: msg
    debug:
      msg: "{{ ps_output }}"