---
- name: Erstelle Snapshots
  hosts: windows_test
  become: false
  gather_facts: true

  tasks:
  - name: Führe PowerShell-Befehl ohne Benutzerprofile aus
    ansible.windows.win_shell: |
      (Get-PSDrive C).free
    register: ps_output
  
  - name: msg
    debug:
      msg: "{{ ps_output.stdout }}"

  - name: msg clean
    set_fact:
      msg_clean: "{{ ps_output.stdout | regex_replace('\r\n', '') }}"

  - name: msg clean clean
    debug:
      msg: "{{ ps_output.stdout | regex_replace('\r', '') }}"