---
- name: Install Heimdall Dashboard
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Prompt for the target server
      vars_prompt:
        - name: server_host
          prompt: "Enter the target server (IP address or hostname):"

    - name: Set facts with user input
      set_fact:
        ansible_host: "{{ server_host }}"

- name: Install Heimdall Dashboard
  hosts: {{ server_host }}
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      tags: ['packages']

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - gnupg
        - software-properties-common
      tags: ['packages']

    - name: Add Heimdall GPG key
      command: curl -sSL https://get.risingstack.com/heimdall.asc | sudo apt-key add -
      tags: ['heimdall']

    - name: Add Heimdall repository
      apt_repository:
        repo: deb https://get.risingstack.com/heimdall / 
      tags: ['heimdall']

    - name: Install Heimdall Dashboard
      apt:
        name: heimdall
        state: present
      tags: ['heimdall']

    - name: Enable and start Heimdall service
      service:
        name: heimdall
        enabled: yes
        state: started
      tags: ['heimdall']

    - name: Cleanup GPG key
      command: apt-key del 79921807
      tags: ['heimdall']

    - name: Remove unnecessary packages
      apt:
        name: "{{ item }}"
        state: purged
      with_items:
        - curl
        - gnupg
        - software-properties-common
      tags: ['packages']

    - name: Reboot the server
      command: reboot
      async: 0
      poll: 0
      ignore_errors: yes
      tags: ['reboot']

  handlers:
    - name: Wait for server to come back
      wait_for_connection:
        timeout: 300
      tags: ['reboot']
