- name: Starte den Ansible-Controller neu und zeige eine Nachricht an
  hosts: localhost
  become: yes
  tasks:
    - name: Starte den Controller neu
      ansible.builtin.reboot:

    - name: Warte auf den Controller, um wieder online zu sein
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300

    - name: Zeige eine Nachricht an
      ansible.builtin.debug:
        msg: "Hello World"
