---
- name: Patch Windows Host
  hosts: "{{ target_hosts }}"
  become: false
  gather_facts: true

  vars_prompt:
  - name: ansible_user 
    prompt: "Admin (bsp. adminjs@gutingia.local)"
    private: false
  - name: ansible_password
    prompt: "Passwort"
    private: true

  tasks:
  - include_tasks: tasks/task-get-windows-services.yml
    ignore_errors: yes
  
  - include_tasks: tasks/task-stop-windows-services.yml
    ignore_errors: yes

  - include_tasks: tasks/task-start-windows-services.yml
    ignore_errors: yes