---
- name: Erstelle Snapshots
  hosts: windows_test
  become: false
  gather_facts: true

  tasks:
  - name: Führe PowerShell-Befehl ohne Benutzerprofile aus
    ansible.windows.win_powershell:
      script: |
        (Get-PSDrive C).free
    register: ps_output
  
  - name: msg
    debug:
      msg: "{{ ps_output }}"