---
- name: Patch Windows Host
  hosts: "{{ target_hosts }}"
  become: false
  gather_facts: true

  vars_prompt:
  - name: ansible_user 
    prompt: "Admin (bsp. adminjs@gutingia.local)"
    private: false
  - name: ansible_password
    prompt: "Passwort"
    private: true
  
  vars:
    vcenter_hostname: vcenter1.gutingia.local
    datacenter_name: myLife

  tasks:
  - name: Get service status (Windows)
    ansible.windows.win_service_info:
      name: "{{ item }}"
    register: service_info
    loop:
      - Spooler
      - CogonCalculationService
      - CogonCommonService
      - CogonCommunicationService
      - CogonMonitoringProcess
      - CogonPathMonitoringService
      - CogonReportingService
      - CogonServiceManager
      - CogonShadowAccountingService

  - name: msg
    debug:
      msg: "{{ item.state }}"
    loop: "{{ service_info.results }}"
    when: 
      - item.exists
      #- item.state == 'running'

  # - name: Stoppe Dienste, die existieren und laufen
  #   ansible.windows.win_service:
  #     name: "{{ item.item }}"
  #     state: stopped
  #   loop: "{{ service_info.results }}"
  #   when: 
  #     - service_info is defined
  #     - service_info.state == 'running'