---
- name: Patch Windows Host
  hosts: "{{ target_hosts }}"
  become: false
  gather_facts: true

  vars_prompt:
  - name: ansible_user 
    prompt: "Admin (bsp. adminjs@gutingia.local)"
    private: false
  - name: ansible_password
    prompt: "Passwort"
    private: true
  
  vars:
    vcenter_hostname: vcenter1.gutingia.local
    datacenter_name: myLife

  tasks:
  - name: Get service status (Windows)
    ansible.windows.win_service_info:
      name: "{{ item }}"
    register: service_info
    loop:
      - Spooler
      - CogonCalculationService
      - CogonCommonService
      - CogonCommunicationService
      - CogonMonitoringProcess
      - CogonPathMonitoringService
      - CogonReportingService
      - CogonServiceManager
      - CogonShadowAccountingService

  - name: msg
    debug:
      msg: "{{ service_info }}" # not required. The customized message that is printed. If omitted, prints a generic message.

  - name: Stop services (Windows)
    ansible.windows.win_service:
      name: "{{ item.item }}"
      state: stopped
    when: 
      - item.exists
      - item.state == 'running'
    loop: "{{ service_info.results }}"