---
- name: Patch Host
  
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
    - include_tasks: tasks/linux/write-log.yml
    - include_tasks: tasks/linux/dist-upgrade.yml
    - name: Dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false
      register: reboot_required_file

    - name: Reboot msg
      ansible.builtin.debug:
        msg: Reboot {{ inventory_hostname }} after the playbook finished.
      when: reboot_required_file.stat.exists == true

    - name: Autoremove
      ansible.builtin.apt:
        autoremove: true

    - name: Autoclean
      ansible.builtin.apt:
        autoclean: true

- name: Patch Linux Server
  
  hosts: linux_server
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  - include_tasks: tasks/linux/write-log.yml
  - include_tasks: tasks/linux/dist-upgrade.yml

  - name: Check reboot
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_md5: false
    register: reboot_required_file

  - name: Reboot
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  - name: Autoremove
    ansible.builtin.apt:
      autoremove: true

  - name: Autoclean
    ansible.builtin.apt:
      autoclean: true